# Generated by Django 4.2.30 on 2026-06-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
