# Generated by Django 4.2.30 on 2026-06-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('waafi', 'Waafi'), ('evc_plus', 'Evc Plus'), ('cash', 'Cash'), ('wallet', 'Wallet'), ('bank', 'Bank'), ('margent', 'MarGENT'), ('card', 'Card')], default='cash', max_length=20),
        ),
    ]
